apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: fdx-agents
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: fdx-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: fdx-config
              key: NODE_ENV
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: fdx-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: fdx-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: fdx-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: fdx-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fdx-secrets
              key: DB_PASSWORD
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: fdx-config
              key: REDIS_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: fdx-secrets
              key: JWT_SECRET
        - name: BACKUP_ENABLED
          valueFrom:
            configMapKeyRef:
              name: fdx-config
              key: BACKUP_ENABLED
        - name: BACKUP_ENCRYPTION
          valueFrom:
            configMapKeyRef:
              name: fdx-config
              key: BACKUP_ENCRYPTION
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: logs-storage
          mountPath: /app/logs
        - name: uploads-storage
          mountPath: /app/uploads
        - name: backups-storage
          mountPath: /app/backups
      volumes:
      - name: logs-storage
        persistentVolumeClaim:
          claimName: logs-pvc
      - name: uploads-storage
        persistentVolumeClaim:
          claimName: uploads-pvc
      - name: backups-storage
        persistentVolumeClaim:
          claimName: backups-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: fdx-agents
spec:
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  namespace: fdx-agents
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
  namespace: fdx-agents
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backups-pvc
  namespace: fdx-agents
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi